### ISSUE TITLE
Integration of thirdparty libraries into build tree

### ISSUE THREAD

**Issue by bendelec** [continental/ecal#11]
Point for discussion 

I believe providing mechanisms to build very common/widespread third party libraries like protobuf and asio in-tree as part of the ecal build process is not best practice. 

It might be a welcome crutch for quick installation on a developer's local system. But for proper deployment on a target, the dependencies should be explicitly handled. There is a high chance that the user will also need other (non ecal) components that depend on these libraries. Other (incompatible) versions of these libraries might already pre-exist on the target systems. With the possibility to build in-tree (ECAL_THIRDPARTY_BUILD...), developers will be lead into using this, and might end up with duplicate libraries on a resource restricted embedded target. Better to clearly specify the dependencies, and have the developers or integrators do their work.

I am a little on the fence on less prevalent and/or possibly outdated third party dependencies (for example simpleini). For these cases, it might be more reasonable to provide them in-tree (in some cases maybe even going as far as having a copy in-tree, not as git sub-modules). But in general, I think best practice is to make third party dependencies explicit, document them well, and have the developer handle them.

This has the added side-effect of keeping the CMakeLists.txt structure a bit simpler. The ecal one is complicated enough as it is ;)

**Comment by Kerstin-Keller** [comment]
Hi @bendelec, 

I totally get your point, from the view of an experienced (I guess Linux) embedded developer.

But I think that there might also be a lot of other developers, who just quickly want to build eCAL and see if this project fits their needs. And it should be fairly easy for everyone to clone the repo including submodules, build the whole thing and then start evaluating.
If you have a whole long list of dependencies to install (especially when you're in a Windows based environment which does not have any package mangers - and where it's not trivial to build and install a library in such a way that it will be located from CMake afterwards), that innitial effort may be too high for newcomers to get started and they might not continue evaluating eCAL.

On the other hand, if you're an experienced developer, you can easily disable building the thirdparty dependencies by passing the correct flags (`ECAL_THIRDPARTY_BUILD_xxx`) to CMake.
So far we only give the option to take a system wide protobuf installation (because it is the only one that has to be build vs header only), but we are free to add these options also for `asio` and `tclap`.

Also we will make sure that all these CMake options will be properly documented.

**Comment by bendelec** [comment]
Hi @Kerstin-Keller,
I was actually thinking about the less experienced developers specifically. An experienced developer will do the right thing anyway. But a less experienced developer will be lead into shortcuts that will come back to haunt him later when their system gets more complex and there are other components driving conflicting dependencies...

But I have to admit, I haven't had the need to develop on or for Windows for many years. If it is really such a hassle in the windows world otherwise, then I agree that some compromises have to be made to accommodate the unfortunate souls who are forced to develop in such an uncomfortable environment :D ... So be it.

**Comment by rex-schilasky** [comment]
Conan integration started. So hopefully we get rid for some of the "internal" third party dependencies.

**Comment by rex-schilasky** [comment]
For linux builds all builtin (none header only) thirdparty git submodules can be deactivated by setting the appropriate CMake options to OFF. So we have a nice comfortable solution for windows users to use the submodules and build them inside the repository and for linux user to use the system installed dependencies. No more need to invest more effort here.
If conan will replace both solutions in the future will be decided later.
