### ISSUE TITLE
Create Dockerfile according to setup docs fails

### ISSUE THREAD

**Issue by markope** [continental/ecal#14]
According to the documentation this Dockerfile should work.

The installation breaks at the cmake command. 

```Dockerfile
FROM debian:latest

RUN apt-get update && apt-get install -y \
	git \
	cmake \
	doxygen \
	graphviz \
	build-essential \
	zlib1g-dev \
	qt5-default

RUN git clone --recursive --depth 1 git://github.com/continental/ecal.git

RUN cd /ecal && \
	mkdir _build && \
	cd _build && \
	cmake .. -DCMAKE_BUILD_TYPE=Release && \
	make -j && \
	cpack -G DEB && \
	sudo dpkg -i eCAL*

CMD ["sleep", "infinity"]
```

## Feature request:
It would be great if you could create a Dockerfile like this with a working installation.

**Comment by Kerstin-Keller** [comment]
Hi @markope,

I agree that this could be helpful for many, we will put it on our list.

I the meanwhile, what is the exact error which your are getting?

I am not quite familiar with debian releases and especially the CMake version distributed with it.
Depending on which components are build, different CMake versions are required.

No documentation, no cpack -> 3.5.1 is fine
Documentation -> >= 3.9 required
Proper cpack: -> >= 3.? required

We recommend always to use a recent CMake version, CMake does have a ppa (ubuntu only I guess https://blog.kitware.com/ubuntu-cmake-repository-now-available/)

Also inside a docker container, it might be easier to use a `make install` instead of `cpack -G DEB && sudo dpkg -i eCAL*` because you won't want to remove packages later, you will just "throw away" the whole container.

**Comment by markope** [comment]
Ok, this dockerfile below works

```dockerfile
FROM ubuntu

RUN apt-get update && apt-get install -y \
	git \
	cmake \
	doxygen \
	graphviz \
	build-essential \
	zlib1g-dev \
	qt5-default

RUN git clone --recursive -j8 git://github.com/continental/ecal.git

RUN cd /ecal && \
	mkdir _build && \
	cd _build && \
	cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_DOCS=OFF && \
	make && \
	make install  && \
	ldconfig

CMD ["sleep", "infinity"]
```

**Comment by rex-schilasky** [comment]
@markope : Thank you for that contribution ! I will close that issue now.
