### ISSUE TITLE
Cannot install the debian file on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by famkoc** [continental/ecal#15]
I have the following Error during the installation: 
`(Lese Datenbank ... 236012 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von eCAL-5.3.4-Linux.deb ...
Entpacken von ecal (5.3.4) ...
dpkg: Fehler beim Bearbeiten des Archivs eCAL-5.3.4-Linux.deb (--install):
 Versuch, »/usr/include/google/protobuf/descriptor.h« zu überschreiben, welches auch in Paket libprotobuf-dev:amd64 2.6.1-1.3 ist
dpkg-deb: Fehler: Unterprozess einfügen wurde durch Signal (Broken pipe) getötet
Fehler traten auf beim Bearbeiten von:
 eCAL-5.3.4-Linux.deb`

How can I fix it?

**Comment by rex-schilasky** [comment]
Hi @famkoc, by default eCAL ships it dependencies inside the thirdparty sub folder as git submodules and is using them to link against. This approach has advantages and disadvantages and was discussed in another issue.
In your case the installed protobuf library is   conflicting with the library version that is checked out in the mentioned third party folder.
You can force cmake to use the installed version by switching off the cmake parameter ECAL_THIRDPARTY_BUILD_PROTOBUF. Then the conflict should be solved.
Second option would be to uninstall the 2.6 version of protobuf from your system (that could be a bad idea because there is for sure another software package depending on that version of protobuf).

**Comment by famkoc** [comment]
OK, also I delete my _build Folder and change the cmake Parameter **ECAL_THIRDPARTY_BUILD_PROTOBUF** to OFF in cmakelist.txt Then I do every step again? 
If I do this, I became the Error durring **make -j**: `tal error: google/protobuf/compiler/parser.h: No such file or directory
compilation terminated.
contrib/ecalproto/src/CMakeFiles/proto.dir/build.make:86: recipe for target 'contrib/ecalproto/src/CMakeFiles/proto.dir/ecal_proto_dyn.cpp.o' failed
`

**Comment by Kerstin-Keller** [comment]
Yes, this is really a problem with Ubuntu 16.04, which ships a really old protobuf version (2.6.1), but eCAL requires protobuf > 3.0. 
If you can, switching to Ubuntu 18.04 might make things easier, because the system protobuf package fullfills ecals requirements.

Also protobuf and CPack don't play together nicely. 
Therefor I would recommend the following:
Download recent protobuf sources (we always tested with 3.5.1) and  build protobuf from source.
Then create a debian package using checkinstall.

```
git clone https://github.com/google/protobuf.git
cd protobuf
git checkout 3.5.1.1
./autogen
./configure "CFLAGS=-fPIC" "CXXFLAGS=-fPIC"
make -j8
make check -j8
checkinstall --pkgname libprotobuf3-dev --pkgversion 3.5.1.1 --pkgrelease 2 --pkglicense "BSD" --provides libprotobuf3-dev --default --fstrans=yes --maintainer \"some_email@domain.com\" --default --exclude \"/home\" --install=no
```

This will create a .deb file for you which you can install with 
```
sudo dpkg -i <name-of-deb>.deb
sudo ldconfig
```

Unlike with CPack, checkinstall will install everything to `usr/local` instead of `usr` so you won't get into trouble with conflicting headers.

If you don't care about your system, you can also just do `sudo make install` instead of creating a debian package :wink:

 After these steps, eCAL should compile successfully (with `ECAL_THIRDPARTY_BUILD_PROTOBUF` to `OFF`)

**Comment by rex-schilasky** [comment]
@famkoc : Did you succeed to solve that issue following @Kerstin-Keller tutorial ?
