### ISSUE TITLE
protobuf option optimize_for = LITE_RUNTIME

### ISSUE THREAD

**Issue by xR3b0rn** [continental/ecal#258]
The helper function `GetProtoMessageDescription` uses a `google::protobuf::Message`-reference to get some information about the protobuf message.

This works fine with generated files using the protobuf default settings. However, when generating the protobuf source files with the `option optimize_for = LITE_RUNTIME;`-option activated, it seems like the generated messages does not use the `google::protobuf::Message` as base class anymore. Thus the build ends in compiler errors.

I think this is a bug and I guess to fix this you have to provide templated functions checking for the right base class. Currently I am fine with removing this option from my protobuf-file.

To reproduce the error, you have to add  `option optimize_for = LITE_RUNTIME;` to one of your protobuf files and use the generated classes with the `eCAL::protobuf::CSubscriber`.

**Comment by FlorianReimold** [comment]
I reproduces the error using [eCAL Hello World Protobuf](https://continental.github.io/ecal/getting_started/hello_world_proto.html#protobuf-sender). For future reference, here is the error:

```
[ 25%] Running C++ protocol buffer compiler on /home/florian/Desktop/hello world proto/proto_messages/hello_world.proto
Scanning dependencies of target protobuf_snd
[ 50%] Building CXX object CMakeFiles/protobuf_snd.dir/main.cpp.o
In file included from /home/florian/Desktop/hello world proto/protobuf_snd/main.cpp:2:
/usr/include/ecal/msg/protobuf/publisher.h: In instantiation of ‘std::string eCAL::protobuf::CPublisher<T>::GetDescription() const [with T = proto_messages::HelloWorld; std::string = std::__cxx11::basic_string<char>]’:
/usr/include/ecal/msg/protobuf/publisher.h:71:97:   required from ‘eCAL::protobuf::CPublisher<T>::CPublisher(const string&) [with T = proto_messages::HelloWorld; std::string = std::__cxx11::basic_string<char>]’
/home/florian/Desktop/hello world proto/protobuf_snd/main.cpp:13:90:   required from here
/usr/include/ecal/msg/protobuf/publisher.h:127:53: error: invalid initialization of reference of type ‘const google::protobuf::Message&’ from expression of type ‘proto_messages::HelloWorld’
  127 |         return(protobuf::GetProtoMessageDescription(msg));
      |                                                     ^~~
In file included from /usr/include/ecal/msg/protobuf/publisher.h:28,
                 from /home/florian/Desktop/hello world proto/protobuf_snd/main.cpp:2:
/usr/include/ecal/protobuf/ecal_proto_hlp.h:130:82: note: in passing argument 1 of ‘std::string eCAL::protobuf::GetProtoMessageDescription(const google::protobuf::Message&)’
  130 |   inline std::string GetProtoMessageDescription(const google::protobuf::Message& msg_)
      |                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
make[2]: *** [CMakeFiles/protobuf_snd.dir/build.make:71: CMakeFiles/protobuf_snd.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/protobuf_snd.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

I haven't done a lot of research about protobuf-lite, but to my understanding it is the same as protobuf minus some features like reflection, right? Because the eCAL Protobuf Publisher and Subscriber both rely on the reflection description string, as their main advantage over a raw byte-blob Subscriber and Publisher is that they include that string. The reflection allows you to dynamically deserialize and inspect the data in the eCAL Recorder (and other tools).

Why did you initially set the LITE_RUNTIME option? Are there some advantages (or disadvantages over "real" protobuf) that I am missing at the moment?

Regards
Florian

**Comment by xR3b0rn** [comment]
`LITE_RUNTIME` optimizes the generated code for fast accessors and omits reflection code:
https://stackoverflow.com/questions/4438977/which-protobuf-optimization

I did not know that ecal depends on protobufs reflection. I only want the fastes code protobuf can generate, i.e. I could stick on `option optimize_for = SPEED;`. However, I did not try the SPEED option yet.

**Comment by rex-schilasky** [comment]
eCAL itself is not depending on the protobuf reflection. The ```LITE_RUNTIME``` option will not generate functions that do provide the so called protobuf file descriptors. These descriptors are then forwarded by the high level templated protobuf publisher class as common "topic description". This topic description then can be used by apps like the eCAL monitor to provide reflection for live data monitoring.
So one option to use ```LITE_RUNTIME``` and eCAL pub/sub is to not use the ```eCAL::protobuf::CPublisher|CSubscriber``` classes but to use the lower level binary API ```eCAL::CPublisher|CSubscriber``` instead or the string variant ```eCAL::string::CPublisher|CSubscriber``` and do the serialization and deserialization yourself on both sides.

**Comment by FlorianReimold** [comment]
Yes, with "Rely on reflection string" I meant rely on the method returning the reflection string being present.

The best example of what the reflection is used for is the eCAL Monitor. The content of a message can only be displayed using the reflection string, as the Monitor would not know how to interpret the data otherwise:
https://continental.github.io/ecal/getting_started/monitor.html#topics

Btw, I checked whether the eCAL Hello World Protobuf example compiles with the `SPEED` option. It does. The reflection works fine.
