### ISSUE TITLE
Side Question: Usage of eclipse-iceoryx / iceoryx ?

### ISSUE THREAD

**Issue by fei4xu** [continental/ecal#326]
Hi,

I happened to see eCAL is mentioned on `eclipse-iceoryx / iceoryx`

https://github.com/eclipse-iceoryx/iceoryx

It says:

<html>
<body>
<h3 style="box-sizing: border-box; margin-bottom: 16px; margin-top: 24px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Where is Eclipse iceoryx used?</h3>

Framework | Description
-- | --
eCAL | Open-source framework from Continental AG supporting pub/sub and various message protocols

</body>
</html>

Just curious, I searched in the eCAL source code to check if iceoryx exists and found that iceoryx is indeed in the source by a compiler options of `ECAL_LAYER_ICEORYX`, which is OFF by default.

Also I found a performance benchmark at doc/rst/advanced/performance.rst which shows that eCAL will have better performance (less latency) with iceoryx when payload > 32kB.

So here I have several questions just out of my curiosity: 

Is there any guideline of enabling iceoryx ? 

Does eCAL has any plan to keep it as an option as it is or enable it by default or  drop it out from eCAL?

Thanks

**Comment by rex-schilasky** [comment]
Hi, thank you for asking. Yes iceoryx can be used as a replacement for eCAL's own shared memory ipc layer. By setting the mentioned CMake option you can now use that eCAL/iceoryx combination on Windows and Linux, since iceoryx 1.0.0 supports both platforms now.
The reason why we do not use it as a default shared memory ipc layer is the fact, that iceoryx is conceptional different from eCAL ipc implementation. eCAL is working fully demonless (no connection match maker, broker ...) and we have many productive systems that should work as expected with every new eCAL release.
But as I mentioned, iceoryx can be switched on easily and the good news is .. you are then still able to use eCAL's wonderful eco system (monitor, recorder, player ...).
Regarding performance in general .. yes it's true starting from payload > 32 kB the performance starts to differ. That's why iceoryx is not doing an extra memory copy on the subscriber side. eCAL is doing this copy to fully decouple the callbacks of all subscribing processes and to free the resource "memory file" as fast as possible. So we have a single copy instead zero copy system here ;-). Maybe we can change the memory file implementation that way that we use a single-write / multiple read pattern. Then the performance is on the same level. See #322
