### ISSUE TITLE
Service with shared memory

### ISSUE THREAD

**Issue by BobDLA** [continental/ecal#329]
Dear,
   I want to use ecal to implement a camera video service on the local computer and should be with shared memory and zero copy feature. I prefer to using service mode instead of pub/sub mode. 
   Could you help answer below questions?
   * Could I use protobuf and shared memory (zero memroy copy) at the same time?
   * Could I implement it by Service mode + protobuf + zero memory copy ?  
   * Which is the best sample I could start from?
   * If I new block in client stack and want to send to server side by shm, will copy happen from user memory to shared memory?

Thanks for your advice.

**Comment by rex-schilasky** [comment]
Hi,
eCAL services are using ASIO services as underlaying API. They are based on TCP/IP and do not use shared memory. The reason here is that we don't want to reinvent the wheel by implementing our own client / service pattern and TCP/IP is a perfect protocol for a reliable communication (that is important for services for sure).
One possible option would be to combine a protobuf based client / server pattern for your video service and a pub/sub pattern for only transferring the large (?) image payload.
Why do you prefer client/server for your video service ?
Cheers, ReX

**Comment by BobDLA** [comment]
Thanks for your feedback. It's clear that service pattern can't with shared memory.

"Why do you prefer client/server for your video service ?"
I do like to get the result of each image sent and manage the result at source side. The sub side is slow than pub side. In the pub/sub pattern, seems pub side don't know the sub side is busy, if data trigger at the time, the sub side will drop the data.
* Is there any configure to make the sub side not loss any package? 
* Is that possible to make it like a FIFO between sub/pub?
* Could you explain the QOS setting which seems not included in the document ?

Thank you again.

**Comment by rex-schilasky** [comment]
Pub/Sub is working with BEST_EFFORT only, that means messages can be dropped if the subscriber side is processing to slow. Over the last years of using eCAL in Continentals AD vehicle fleet we figured out that loosing a single frame is often not that critical but any kind of latency in the data flow is very critical for the overall system performance. That is the reason we did not work further on QOS but focused more on best (effort) performance.

There are options to set kind of acknowledge handshake timings (default is off) in the eCAL ini configuration file, but I would not recommend to do so. If your subscriber is to slow in general you should think about your system setup (publication frequency for example). Instead of providing a FIFO inside the eCAL core we recommend to implement this if needed on the user application level. So in your message callback you should store the message content in your own container and return asap. So the publisher can start writing immediately and the subscribing application can work on your FIFO queue in another thread.

**Comment by BobDLA** [comment]
Thanks for your answer. I will try it.
