### ISSUE TITLE
Documentation on Threading Model is Missing

### ISSUE THREAD

**Issue by bsirang** [continental/ecal#370]
I am new to eCAL, and I am trying to better understand how to develop applications on top of it. I read through the documentation at https://continental.github.io/ecal/ and I didn't notice any sections on threading models.

I am trying to understand questions like:

1. Do timer callbacks and subscriber callbacks execute on the same thread?
2. What thread do service calls run on? Is there a thread pool involved?
3. When is it acceptable to block on I/O? When is it not?
4. How is ASIO used under the hood? If an eCAL user wanted to use ASIO for their own asynchronous I/O, is there a clean way to mix with eCAL to reuse event loop threads?

**Describe the solution you'd like**
A page added to the documentation that addresses all the questions above.

**Describe alternatives you've considered**
I can't think of a good alternative.

**Comment by rex-schilasky** [comment]
Documented https://continental.github.io/ecal/advanced/threading_model.html

**Comment by bsirang** [comment]
Thanks @rex-schilasky !

I did notice one typo `startet` -> `started`

**Comment by rex-schilasky** [comment]
@bsirang Thank you, just saw the typo after the merge was done. Currently the CI is triggering a full build for every push/ pull request. That's why I was not that motivated to correct this single letter :-D. We really need a independent build for documentation changes only. But I hope the documentation helps .. some more internal docs will follow.
