### ISSUE TITLE
ecalsys: start application with gdb on linux

### ISSUE THREAD

**Issue by julien-seitz** [continental/ecal#401]
**Is your feature request related to a problem? Please describe.**
Given the situation that a application that has been started via eCAL crashes, it might be helpful to analyze this crash with an debugger and/or to create a stacktrace.
To achieve that, it's necessary to open a terminal window, to navigate to the working directory, copy the path to the executable and the command line arguments to the terminal and execute the same command using gdb. Like mentioned, this requires some manual steps.

**Describe the solution you'd like**
It would be helpful, if there is a possibility to directly start the same executable with the same command line arguments in the same environment and same working directory just by selecting an additional checkbox.

**Describe alternatives you've considered**
Maybe there is another way to create stacktraces automatically in case of an error. I know that this is possible on windows.

**Comment by FlorianReimold** [comment]
Hi Julien,

With eCAL you mean eCAL Sys, right? eCAL Sys since eCAL 5.9 displays a preview in the GUI, where it tells you the command line it will use to start an application (evaluated on the PC the GUI is running on, obviously). You can copy that string to a terminal to start your application with a debugger. You can also create a runner, which automatically starts the application with a debugger. But I am not sure if that is really helpfull, as the terminal should not be interactive by default...

![sys](https://user-images.githubusercontent.com/11774314/134338461-5e2eb8a8-cced-4c20-a4a2-27b715d299aa.png)

Regards
Florian

**Comment by julien-seitz** [comment]
ah that's very helpful already.
Yes that's right: With eCalSys it would not be interactive.
Thus, I'm not sure if a separate Runner would be an option.
However, would it be possible to create a complete command that would be necessary to execute the application with gdb like:

cd /path/to/workdir && gdb -ex run --args ./a.out arg1 arg2 ...

and provide the possibility to copy that command?

**Comment by FlorianReimold** [comment]
Well, when configuring the runner with the example options you wrote, you would get:

![sys](https://user-images.githubusercontent.com/11774314/134341359-42dff7b7-e9dd-46e6-92f9-e1999b4f31d8.png)

You still have to copy the working dir and the executable command line separately, but otherwise it is basically what you wrote.

**Comment by julien-seitz** [comment]
just thinking about if it would be possible to have a button for the gdb command.
When clicking on that, the user gets a pop-up containing the command to start gdb.
![image](https://user-images.githubusercontent.com/79102583/134343383-b85b772c-6168-475d-9c0e-546735fd7879.png)

Purpose of that would be to make it as easy as possible for the user to start the debugger. (so that even a non-developer is able to start this application)
Regarding the approach with the Runners I currently see some drawbacks:
If the application is already using another Runner, than it's not possible to combine this with the gdb-functionality.
Additionally, the gdb functionality might need to be configured manually in advance.

**Comment by julien-seitz** [comment]
maybe even a addition to that proposal:
Typically if a application does not start up properly, the developer typically tries to recreate the command line to start up the application from the terminal. Then he executes the command and looks at the output in the terminal to identify the problem.

Also for that functionality, it might be helpful to have the possibility to directly copy the concatenated command to start the application from outside of ecalsys

**Comment by FlorianReimold** [comment]
I am closing this issue, as space in a GUI is worth a lot and implementing this very specialized button doesn't feel right. It can be "emulated" in a few settings by typing `gdb -ex run --args` by hand and then pasting the command line displayed in the eCAL Sys GUI.

If more users request this feature, we may still add it in the future, but for now I don't really see the necessity
