### ISSUE TITLE
Regarding Conan dependencies.

### ISSUE THREAD

**Issue by photex** [continental/ecal#54]
The current conanfile.txt in this repo is using packages that are not automatically or easily resolved.

It would be helpful to know where kwc_bintray is and add this to the README so that others can use Conan.

Digging around the commit and issue history I see that this was contributed by someone from Kai Wolf (so kwc seems to make sense). So it appears as though they have a self-hosted artifactory service but not all the packages were listed. At which point I realized that it's probably https://bintray.com/kwc which is rather easy in hindsight.

Running `conan remote add kwc_bintray https://api.bintray.com/conan/kwc/conan` resolved this for me.

Then you apparently also need bincrafters:
`conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan`

But you finally end up with the issue of the version of protobuf being requested is not apparently available in the bincrafters public conan repository. However, the requested version is available on conan-center. *But* still missing is protoc_installer.

It would be useful to add some documentation for the level of Conan support in the repo and how to use it.

**Comment by Kerstin-Keller** [comment]
Hi @photex,

I totally agree that Conan integration is not smooth yet. We worked together with @NewProggie to the Conan integration.
Unlike the behavior you get from Conan Center packages, we want the Conan integration to be truly optional. E.g. only the `cmake_paths`  generator should be used. (e.g. all target names used in CMake should be identical to those that you get by `pure` CMake installs).

This is why many packages were repackaged instead of using the official packages.

However, the current recommendation to build eCAL is to use submodule integration for thirdparty dependencies for an easy build on Windows, and on Linux use packages provided by the system package manager when available (e.g. on Ubuntu 18.04, hdf5, protobuf, qt, … can all be retrieved by apt-get).

More experienced users can use any way to provide the necessary dependencies.

But it still makes sense to put a chapter in the Readme file on Conan support / integration.

> However, the requested version is available on conan-center. But still missing is protoc_installer.

Conan Center decided to package `protoc` and `protobuf` separately, mainly to facilitate cross-builds. With the `kwc` packages, they are packaged together (which I think they should be. Since they belong together, they are always required in the same version).

**Comment by NewProggie** [comment]
Good catch. I think there should be another section in the README.md containing:

```
# Install Conan
$ pip install --upgrade pip
$ pip install --upgrade conan
$ conan config set general.revisions_enabled=True

# Add Conan remotes with pre-compiled dependencies
$ conan remote add -f kwc_bintray https://api.bintray.com/conan/kwc/conan
$ conan remote add -f conan-center https://bintray.com/conan/conan-center
$ conan remote add -f bincrafters https://api.bintray.com/conan/bincrafters/public-conan
```
Let me quickly add another PR for this.

**Comment by photex** [comment]
Thanks for the explanations.

@NewProggie neither bincrafters or conan-center had protoc_installer for the specified version when I tried it today. Can you verify that this works with these remotes?

**Comment by gocarlos** [comment]
actually the packages in the conan center are now being reworked to allow transparent conan usage, e.g. same target names of the packages when installed and found via cmake... 

if some package is still not work this way, its a bug in the package that needs fixing...

**Comment by FlorianReimold** [comment]
Closing this discussion-thread due to inactivity
