### ISSUE TITLE
Warning about missing ecal time plugins

### ISSUE THREAD

**Issue by siggie0815** [continental/ecal#609]
**Describe the bug**
When building eCAL explicitly without the time plugins. My applications always complains about the missing time plugin. The fallback to local time works fine, though.

**To Reproduce**
- build eCAL with `-DBUILD_TIME=OFF`
- Build and link any application against your eCAL
- Run the application
- Observe following warning: `Could not load eCAL time sync module libecaltime-localtime.so`

**Expected behavior**
When explicitly built without time plugins, the warning should be deactivated.

**Comment by FlorianReimold** [comment]
Hi siggie0815,

I think I disagree with your proposed solution. Especially when not building the time plugins you want to have the warning, as it tells you that something is missing. The `ecal.ini` points to a non-existing time module and there should be a warning about that. Also you may want to provide your own timesync module and use that instead of what eCAL comes with by default.

My proposed solution is to support not setting any timesync module at all and make eCAL fall back to the internal local time (which is exactly what `ecaltime-localtime` does anyways, I believe).

So when your `ecal.ini` states
``` ini
[time]
timesync_module_rt        = 
```

it will fall back without complaining and giving a warning.

Would that solution be fine for your case?

Regards
Florian

**Comment by siggie0815** [comment]
Hey,
jepp, that sounds good and seems to make the warning disappear.

However one could argue that in this case the installed ecal.ini should be directly as you suggested.

But for now I'm fine.

Thanks a lot
