### ISSUE TITLE
Python service doesn't work

### ISSUE THREAD

**Issue by HadiSheybani** [continental/ecal#626]
The Python simple service example does not work. I try to use service in python program, but it stuck.

example output is:

eCAL v5.9.5 (2022-02-23 17:20:10 +0100)

CUDPSender: Setting TTL failed: Invalid argument
CUDPSender: Setting TTL failed: Invalid argument
'DemoService' method 'foo' requested with : b'hello foo 1'

what should I do? I tried different config but it doesn't work

**Comment by rex-schilasky** [comment]
This issue is the same like #244. The problem is still not solved, it's based on the fact that both server and client run in the same python unit and the needed threading is locked by the [Python Global Interpreter Lock](https://realpython.com/python-gil/).

I will split that demo in two separate units for now (client / server) to demonstrate a working sample.

**Comment by rex-schilasky** [comment]
@HadiSheybani see changed [minimal service implementation](https://github.com/continental/ecal/tree/hotfix/python_service_sample_gil/samples/python/minimal_service).
