### ISSUE TITLE
Travis CI integration

### ISSUE THREAD

**Issue by rex-schilasky** [continental/ecal#8]
eCAL should use Travis CI to check builds for all supported platforms.

**Comment by hannemn** [comment]
Since Travis CI has a very bad support for QT on Windows, it makes sense to extend the build check with AppVeyor CI for the windows platform. On the other hand the build for posix systems like Linux or macOS should be done with Travis, because these platforms are very well supported by this CI tool.

**Comment by hannemn** [comment]
Windows and Linux CI has been added with PR #9

**Comment by rex-schilasky** [comment]
Travis CI build for linux os working. For windows we need to deploy the qt library in any way.

**Comment by rex-schilasky** [comment]
AppVeyor integrated for Windows builds.
